[package]
authors = ["\nShinyzenith <https://shinyzenith.xyz> ", " Cmeissl <https://github.com/cmeissl> ", " Victor Berger <https://github.com/vberger>"]
description = "Screenshot tool for wlroots based compositors implementing the zwlr_screencopy_v1 protocol."
documentation = "https://git.sr.ht/~shinyzenith/wayshot"
edition = "2021"
homepage = "https://waycrate.shinyzenith.xyz"
keywords = ["screenshot", "wayland", "wlroots"]
license = "BSD-2-Clause"
name = "wayshot"
repository = "https://git.sr.ht/~shinyzenith/wayshot"
version = "1.1.0"
exclude = [
    "CODE_OF_CONDUCT.md",
    "CONTRIBUTING.md",
	"contrib/*",
	"docs/*",
	"release.sh",
]

[dependencies]
clap = "3.1"
env_logger = "0.8.4"
image = "0.24"
log = "0.4.0"
memmap2 = "0.2"
nix = "0.20"
smithay-client-toolkit = "0.15.3"
tempfile = "3.3.0"

[[bin]]
name = "wayshot"
path = "src/wayshot.rs"
