[package]
authors = ["\nShinyzenith <https://shinyzenith.xyz> ", " Cmeissl <https://github.com/cmeissl> ", " Victor Berger <https://github.com/vberger>"]
edition = "2021"
name = "wayshot"
version = "0.1.0"

[dependencies]
clap = "3.1"
env_logger = "0.8.4"
image = "0.24"
log = "0.4.0"
memmap2 = "0.2"
nix = "0.20"
smithay-client-toolkit = "0.15.3"
tempfile = "3.3.0"

[[bin]]
name = "wayshot"
path = "src/wayshot.rs"
