[package]
authors = ["Shinyzenith <aakash@shinyzenith.xyz>", "Cmeissl <https://github.com/cmeissl>", "Victor Berger <https://github.com/vberger>"]
edition = "2021"
name = "wayshot"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
image = "0.24"
memmap2 = "0.2"
nix = "0.20"
tempfile = "3.3.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
smithay-client-toolkit = "0.15.3"
clap = "3.0.14"

[[bin]]
name = "wayshot"
path = "src/main.rs"
